export enum ENV {
	DB_HOST = 'DB_HOST',
	DB_PORT = 'DB_PORT',
}

export enum DB_1 {
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_NAME = 'DB_NAME_1'
}


export enum DB_2 {
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_NAME = 'DB_NAME_2'
}

export enum DB_3 {
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_NAME = 'DB_NAME_3'
}
